apiVersion: v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: playfull
    tier: backend
spec:
  selector:
    matchLabels:
      app: playfull
  template:
    metadata:
      labels:
        app: playfull
    spec:
      containers:
      - name: gateway
      - image: ahesselgrave/gateway
        ports:
        - containerPort: 80